package com.digitalacademy.somjai.service

object SlipVerificationDataService {
    var transRef = ""
    var sendingBank = ""
    var receivingBank = ""
    var transDate = ""
    var transTime = ""
    var senderDisplayName = ""
    var senderName = ""
    var senderProxyType = ""
    var senderProxyValue = ""
    var senderAccountType = ""
    var senderAccountValue = ""
    var receiverDisplayName = ""
    var receiverName = ""
    var receiverProxyType = ""
    var receiverProxyValue = ""
    var receiverAccountType = ""
    var receiverAccountValue = ""
    var amount = ""
    var paidLocalAmount = ""
    var paidLocalCurrency = ""
    var ref1 = ""
    var ref2 = ""
    var ref3 = ""
}